### PR TITLE
Support skipping polling.

### PR DESCRIPTION
**Pull request by iBotPeaches**
fixes: #57

### CODE REVIEW

**Review by joeladam518 — APPROVED** [review]

**Review by nicomaurer — APPROVED** [review]

**Review by chavezellis — APPROVED** [review]
Looks good

**Comment by Samuell1** [comment]
Hey, its now relased under v1 version for actions? I tried it but it doesnt look like it uses new code.

**Comment by iBotPeaches** [comment]
> Hey, its now relased under v1 version for actions? I tried it but it doesnt look like it uses new code.

Not yet. Tag should be moved in a few days. Internal repos run off `master` for a few days to ensure we aren't regression anything before moving v1 tag.

**Comment by iBotPeaches** [comment]
`v1` tag moved to v1.3.0

**Comment by Samuell1** [comment]
@iBotPeaches Thanks a lot! Tested it works very well 👍 

But i think there is issue with colors definition as you can see in screenshots.

image

**Comment by iBotPeaches** [comment]
> But i think there is issue with colors definition as you can see in screenshots.

thanks good find - https://github.com/sourcetoad/aws-codedeploy-action/pull/59

**Pull request merged**
